# 1. 啟動 RabbitMQ + Flower（背景執行）
# docker compose -f docker-compose-local.yml up -d rabbitmq flower
# 2. 看 log 確認啟動成功
# docker logs -f rabbitmq
# docker logs -f flower
# # 3. （今天結束再執行）收工時關閉
# docker compose -f docker-compose.yml stop rabbitmq flower

services: # 定義所有要啟動的服務 
 # ===== Message Broker =====
  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  flower:
    image: mher/flower:2.0
    container_name: flower
    command: ["celery", "--broker=amqp://worker:worker@rabbitmq", "flower", "--port=5555"]
    ports:
      - 5555:5555
    depends_on:
      rabbitmq:
        condition: service_healthy


  # ===== Celery Workers =====
  crawler_twse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawler_twse
    command: uv run celery -A crawler.worker worker --loglevel=info --hostname=twse@%h -Q twse
    environment:
      RABBITMQ_HOST: rabbitmq
      # MYSQL_HOST: mysql
    depends_on:
      rabbitmq:
        condition: service_healthy
      # mysql:
      #   condition: service_healthy
    volumes:
      - ./output:/crawler/output

  crawler_tpex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawler_tpex
    command: uv run celery -A crawler.worker worker --loglevel=info --hostname=tpex@%h -Q tpex
    environment:
      RABBITMQ_HOST: rabbitmq
      # MYSQL_HOST: mysql
    depends_on:
      rabbitmq:
        condition: service_healthy
      # mysql:
      #  condition: service_healthy
    volumes:
      - ./output:/crawler/output
